USE DTX;

CREATE TABLE users
(
    UUID     VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    `role`   VARCHAR(255) NOT NULL,
    fName    VARCHAR(255) NOT NULL,
    lName    VARCHAR(255) NOT NULL,
    enabled BIT NOT NULL DEFAULT 1
);